/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SalesEmployeeRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author akhilsaikoppanatham
 */
public class SalesEmployeeWorkAreaJPanel extends javax.swing.JPanel {
//We have a table here Select row and click SMS to send SMS to the clients for lead generation

    String twilioAuthToken = "b8809bbbd0273aaec88ca928f541a823";
    String receiverNumber = "8573812076";
    String message = "Hello from Your Agent at DriveLine";

    // The Employee Can be able to call the owner of the automobile for lead generation
    public SalesEmployeeWorkAreaJPanel(JPanel rightPanel, Enterprise enterprise, UserAccount account, EcoSystem business) {
        initComponents();
    }
    String twilioURL = "curl -X POST https://api.twilio.com/2010-04-01/Accounts/ACb4f18af468af37ad60d34d9dc103dc32/Messages.json \\\n"
            + "--data-urlencode \"Body=" + message + "\" \\\n"
            + "--data-urlencode \"From=+15719011461\" \\\n"
            + "--data-urlencode \"To=+1" + receiverNumber + "\" \\\n"
            + "-u ACb4f18af468af37ad60d34d9dc103dc32:$" + twilioAuthToken;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
