/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GarageMechanicRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.GarageMechanicOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author akhilsaikoppanatham
 */
public class GarageMechanicWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private GarageMechanicOrganization researchAssistantOrganization;
    private Enterprise enterprise;
    
   /**
     * Creates new form ManageVolunteersJPanel
     * @param userProcessContainer
     * @param account
     * @param enterprise
     * @param business
     */
    public GarageMechanicWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.enterprise=enterprise;
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.researchAssistantOrganization = (GarageMechanicOrganization)organization;
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        check2 = new javax.swing.JButton();
        check3 = new javax.swing.JButton();
        check4 = new javax.swing.JButton();
        check1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        check2.setBackground(new java.awt.Color(255, 255, 204));
        check2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        check2.setText("Check 2");
        check2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check2ActionPerformed(evt);
            }
        });
        add(check2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 210, 150));

        check3.setBackground(new java.awt.Color(255, 255, 204));
        check3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        check3.setText("Check 3");
        check3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check3ActionPerformed(evt);
            }
        });
        add(check3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 200, 160));

        check4.setBackground(new java.awt.Color(255, 255, 204));
        check4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        check4.setText("Check 4");
        check4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check4ActionPerformed(evt);
            }
        });
        add(check4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 690, 210, 150));

        check1.setBackground(new java.awt.Color(255, 255, 204));
        check1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        check1.setText("Check 1");
        check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check1ActionPerformed(evt);
            }
        });
        add(check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 150));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Images/phases.gif"))); // NOI18N
        jPanel2.add(jLabel2);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 820, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void check1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check1ActionPerformed
        // TODO add your handling code here:
        Check1JPanel check1JPanel = new Check1JPanel(userProcessContainer,userAccount,researchAssistantOrganization,enterprise, business);
        userProcessContainer.add("Check1JPanel", check1JPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_check1ActionPerformed

    private void check2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check2ActionPerformed
        // TODO add your handling code here:
        Check2JPanel check2JPanel = new Check2JPanel(userProcessContainer,userAccount,researchAssistantOrganization,enterprise, business);
        userProcessContainer.add("Check2JPanel", check2JPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_check2ActionPerformed

    private void check3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check3ActionPerformed
        // TODO add your handling code here:
        Check3JPanel check3JPanel = new Check3JPanel(userProcessContainer,userAccount,researchAssistantOrganization,enterprise, business);
        userProcessContainer.add("Check3JPanel", check3JPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_check3ActionPerformed

    private void check4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check4ActionPerformed
        // TODO add your handling code here:
        Check4JPanel check4JPanel = new Check4JPanel(userProcessContainer,userAccount,researchAssistantOrganization,enterprise, business);
        userProcessContainer.add("Check4JPanel", check4JPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_check4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton check1;
    private javax.swing.JButton check2;
    private javax.swing.JButton check3;
    private javax.swing.JButton check4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
